### ISSUE TITLE
cant be able to run the project

### ISSUE THREAD

**Issue by mrvyas417** [alper-efe-sahin/social_dating_app#26]
File google-services.json is missing.

**Comment by FlutterWiz** [comment]
Of course it is. You need to create your own firebase project.

**Comment by mrvyas417** [comment]
Okay so can you provide any documentation, what kind of service you use and all structure

**Comment by FlutterWiz** [comment]
> Okay so can you provide any documentation, what kind of service you use and all structure
> 
> 
> 
> 

"This is the first version of the Social Dating App repo. There is no chat feature. For backend, I used Firebase/Firestore (also firestore storage for uploading/downloading files).

Since the firebase project keys are private, I did not share them. If you want to use this application, first you must complete the firebase authentication process."

If you look readme.md, I wrote here. Thanks!
